# Generated by Django 3.1.7 on 2021-04-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classNo', models.CharField(max_length=10)),
                ('className', models.TextField()),
                ('professor', models.CharField(max_length=10)),
                ('classRoomNo', models.CharField(max_length=10)),
            ],
        ),
    ]
